### ISSUE TITLE
topic is not allowed

### ISSUE THREAD

**Issue by Serph91P** [ivanmihov/homeassistant-ntfy.sh#13]
Getting this error when adding topic to the script:

```
error while executing automation automation.waschmaschine_fertig: extra keys not allowed @ data['topic']

**Comment by Knah-Tsaeb** [comment]
Same here.

**Comment by pharmacologic** [comment]
it seems that the provided example in `README.md` is incorrect. 

`topic:` should be under another `data:` block

this works for me:
```yaml
service: notify.ntfy
data:
  title: Battery Alert
  message: phone is currently at {{states('sensor.phone_battery_level')}}% battery.
  data:
    topic: non_default_topic
    tags:
      - telephone_receiver
      - battery
```
