### ISSUE TITLE
400 Bad Request when sending authenticated messages

### ISSUE THREAD

**Issue by wsw70** [ivanmihov/homeassistant-ntfy.sh#14]
I can reach my Ntfy server via

```
curl  -H "Authorization: Bearer tk_..." -d "Look ma, with auth"  https://ntfy.example.com/hass
```

I configured the HACS integration with the following configuration:

```yaml
notify:
  - name: ntfy
    platform: ntfy
    url: https://ntfy.example.com
    token: tk_...
    topic: hass
```

When calling the `notify.ntfy` service as 

![image](https://github.com/ivanmihov/homeassistant-ntfy.sh/assets/1345886/99c088d1-ca8a-472d-bef7-ff075a60ae6d)

I get a `400 Bad Request` entry in the logs:

```
hass-1  | 2024-03-20 17:11:26.932 ERROR (MainThread) [custom_components.ntfy.notify] Error while sending ntfy.sh message: 400 Client Error: Bad Request for url: https://ntfy.example.com/
```
