### ISSUE TITLE
No messages recieved. Is this integration dead or incompatible with newer HA?

### ISSUE THREAD

**Issue by DAE51D** [ivanmihov/homeassistant-ntfy.sh#16]
have this in `configuration.yaml`
```yaml
notify:
  - name: "my ntfy"
    platform: ntfy
    url: http://192.168.1.6
    topic: homeassistant
    #token: <ntfy.sh_token>
    #icon: <notification_icon_url>
```
have this in a simple NFC trigger as a sanity test using built in notifications to verify things are "working" in that regard...
```yaml
action: notify.notify
metadata: {}
data:
  message: testing built in notification from HA
```
I mimic the above message and change `action` 
```yaml
action: notify.my_ntfy
data:
  message: testing ntfy from HA
```
The `notify` one comes through, the `my_ntfy` does not.

My `ntfy` server is functioning fine and I can send/receive messages with this
```bash
curl -d "Hello World. ntfy working!" 192.168.1.6/homeassistant
```

Also, if I try your example instead I get errors (that's why I tried the above format in case something changed as the YAML structure is different than this one slightly)
```yaml
action:
  - service: notify.my_ntfy
    data:
      message: "This is a test message."
```
 **Error in describing action: n.action.split is not a function or its return value is not iterable**
and
**Message malformed: value should be a string for dictionary value @ data['actions'][2]['action']**

I'm using:
Core 2024.10.4
Supervisor 2024.10.3
Operating System 13.2
Frontend 20241002.4

**Comment by baudneo** [comment]
Just added this to my set up and it works fine.

# configuration.yaml > notify:
```
- name: ntfy_cameras
  platform: ntfy
  url: !secret ntfy_url
  token: !secret ntfy_token
  topic: hass_ai_cameras
```

# Action
```
action: notify.ntfy_cameras
data:
  data:
    tags:
      - warning
    priority: 4
    attach: https://companion.home-assistant.io/assets/images/actions-a11b1419f6254c8b98270942e29e327e.png
    filename: filename.jpg
    click: https://www.home-assistant.io/
  message: testing
```

The image wont come through if you dont have the attachments cache enabled, AFAIK. The message should still come through, without the image.

**Comment by DAE51D** [comment]
Okay, thank you for the example. I was able to now get my `ntfy` to work....

in my action, (same as you basically, but adjusted to my setup above)
```yaml
action: notify.homeassistant
data:
  data:
    tags:
      - warning
    priority: 4
    attach: >-
      https://companion.home-assistant.io/assets/images/actions-a11b1419f6254c8b98270942e29e327e.png
    filename: filename.jpg
    click: https://www.home-assistant.io/
  message: testing
```

and in `configuration.yaml`
```yaml
notify:
  - name: general
    platform: ntfy
    url: http://192.168.1.6
    topic: general
  - name: homeassistant
    platform: ntfy
    url: http://192.168.1.6
    topic: homeassistant
```

On my PC desktop I got this
![image](https://github.com/user-attachments/assets/d05cd197-442b-48e4-8f84-c646cb870c3a)

And on my Android phone I got this
![Screenshot_20241212-182358_One UI Home](https://github.com/user-attachments/assets/fb02c46d-9b31-48a2-86fd-a13c7637de56)

So seeing your example made some more sense as to how this works and lines up. Thank you @baudneo
