### ISSUE TITLE
Edit: unknown service: notify.my_ntfy.

### ISSUE THREAD

**Issue by M1K3-NL** [ivanmihov/homeassistant-ntfy.sh#5]
Hello.

The error I get when adding
```
notify:
  - name: "my ntfy"
    platform: ntfy
    url: <ntfy.sh_url>
    token: <ntfy.sh_token>
    topic: <ntfy.sh_topic>
    icon: <notification_icon_url>
```
to the configuration.yaml is:

**Cannot quick reload all YAML configurations because the configuration is not valid: Platform error notify.ntfy - Integration 'ntfy' not found.**

I have added your rep via HACS.
![opera_HcKXTHhHg7](https://github.com/ivanmihov/homeassistant-ntfy.sh/assets/39988281/118c07f9-bf42-48f9-bfac-345015995e90)
![opera_2FrPQTAguL](https://github.com/ivanmihov/homeassistant-ntfy.sh/assets/39988281/db6abe8b-7cba-468f-a7c0-5e50a8e1b833)
