### ISSUE TITLE
Not receiving message with data properties

### ISSUE THREAD

**Issue by bsdev90** [ivanmihov/homeassistant-ntfy.sh#7]
Hi,

I succeed to configure the plugin and send message to my Ntfy via Home Assistant, so thank you for that !
But there is a problem, when I put data properties like "priority" or "click", I don't receive any message.
Here are Home Assistant logs output:
>Logger: custom_components.ntfy.notify
>Source: custom_components/ntfy/notify.py:89
>Integration: ntfy ([documentation](https://github.com/ivanmihov/homeassistant-ntfy.sh), [issues](https://github.com/ivanmihov/homeassistant-ntfy.sh/issues))
>First occurred: 10:29:29 (9 occurrences)
>Last logged: 11:47:53
>
>Error while sending ntfy.sh message: 400 Client Error: Bad Request for url: https://###/

To test, I used your codes snippets (by replacing service by my ntfy service) like this one:
```yaml
action:
  - service: notify.my_ntfy
    data:
      message: "This is a test message."
      title: "ntfy Test"
      data:
        priority: 10
```

**Comment by M1K3-NL** [comment]
How did you rename the service to your own and got it working? It's not working on my end.

**Comment by bsdev90** [comment]
> How did you rename the service to your own and got it working? It's not working on my end.

In the configuration.yaml:
```yaml
notify:
  - name: "Ntfy Test"
    platform: ntfy
    ...
  - name: "Ntfy 3D Print"
    platform: ntfy
    ...
```

You have to restart completly home assistant, after that you can use them directly. In my case:
- notify.ntfy_test
- notify.ntfy_3d_print

Here the action in one of my automation for example:
```
action:
  - service: notify.ntfy_3d_print
```
